<!DOCTYPE html>
<head>
  	<meta charset="utf-8" />
	<title>Nós Mídia - Sobre</title>

	<!-- Included CSS Files -->
	<link rel='stylesheet' href='<?php echo URL ?>/css/mobile.css'>

</head>
<body>
	
	<div class="content single" id="content<?php echo md5($_SERVER['REQUEST_URI']); ?>">
		<div class="post" id="post-about">
			<p style="text-align: center;"><img src="<?php echo URL ?>/images/logo-nos-midia-v2.png" alt="Nós Midia"/></p>
	    	<p style="text-align: center;"><img class="alignnone size-full wp-image-72" title="nos midia" src="http://www.nosmidia.com.br/wp-content/uploads/2012/04/sobre-projeto.jpg" alt="nos midia" width="627" height="321" /></p>
			<p>O programa Nós Mídia é um ponto de encontro entre pessoas, tecnologias de conversação e plataformas digitais. Um lugar para o desenvolvimento de percepções e exercícios de ferramentas para promover a ocupação de espaços digitais para desencadear transformações humanas.</p>
			<p>Embasado nos fundamentos das tecnologias livres e abertas, naturais da internet, o programa promove ações inovadoras que propiciam a formação de multiplicadores ativos, cidadãos críticos dispostos a utilizar todo o potencial da rede para democratizar os meios de comunicação, desenvolver e promover atividades artísticas, culturais e educativas com foco no fomento de empreendimentos digitais criativos.</p>
			<p>Com um amplo espectro de atividades, o Nós Mídia propõe e executa diversos projetos de formação e desenvolvimento de tecnologia em parceria com o poder público, iniciativa privada e sociedade civil, sempre com ênfase no uso criativo e consciente das mídias digitais.</p>
			<p>Entre as atividades e os objetivos do programa estão o desenvolvimento tecnológico de plataformas e ambientes digitais de cunho cultural; produção de conhecimento, publicações digitais interativas, mapeamentos culturais comunitários e a realização de oficinas com foco na formação de multiplicadores da metodologia do projeto.</p>
			<p>Seja bem-vindo e conheça as nossas principais atividades.</p>
	    </div>
	</div>
		
</body>

</html>
