<div class="modal-header">
	<a class="close" data-dismiss="modal">×</a>
	<h3>Como usar</h3>
</div>
<div class="modal-body">
	<p>
		Tenderloin rump filet mignon, pork boudin chuck meatloaf drumstick salami. Ribeye filet mignon shoulder, biltong pork kielbasa pork belly turkey strip steak chicken pork chop pastrami. Salami shoulder flank, frankfurter swine pork belly andouille. Shankle salami brisket cow, beef ribs pastrami fatback hamburger.
	</p>
	<p>
		Leberkas spare ribs boudin, shoulder pig pork belly ham t-bone jowl. Venison andouille leberkas, ham hock sausage capicola boudin turkey shank ground round. Tenderloin venison frankfurter bacon salami. Sirloin spare ribs beef venison, drumstick pork filet mignon rump pork belly tri-tip ham hock andouille. Chicken turkey turducken, meatloaf t-bone beef andouille ham strip steak short ribs. Filet mignon short ribs kielbasa chuck frankfurter speck tri-tip pork loin, fatback beef ribs.
	</p>
</div>
