<?php if($this->categories) : ?>
    <nav class='map-actions categories'>
        <h2>Selecione a categoria:</h2>

        <ul id='menu-category'>
            <?php foreach($this->categories as $category) : ?>
                <li>
                    <a class='<?php echo $category->slug; ?>' id='category_<?php echo $category->id; ?>'>
                        <img src='<?php echo Model_Category::iconUrl( $category->icon_file);  ?>' alt='<?php echo $category->category; ?>'>
                        <?php echo $category->category; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>

    <div id='subcategories' class='subcategories hide'></div>
<?php endif; ?>