<h1>Pontos no Mapa</h1>
<h3>Lista de pontos no mapa</h3>

<?php if( $this->points->count() ): ?>
<table width="100%">
<thead>
	<tr>
		<th class="header" width="10%">Categoria</th>
		<th class="header" width="60%">Conteúdo</th>
		<th class="header" width="20%">Autor</th>
		<th class="header" width="10%">Ações</th>
	</tr>
</thead>

<tbody>
	<?php foreach($this->points as $value ) : ?>
	<?php $delete_url = $this->url(array('module'=>'adm','controller'=>'pontos','action'=>'delete','id'=>$value->id),null,false);?>
	<tr>
		<td class="t-center" style="vertical-align: middle;"><img src="<?php echo '/uploads/icon_file/'.$value->icon_file; ?>" title="<?php echo $this->escape($value->category); ?>" /></td>
		<td style="vertical-align: top;">
			<a href="/adm/pontos/show-content/id/<?php echo $value->id; ?>" onclick="javascript:void window.open('/adm/pontos/show-content/id/<?php echo $value->id; ?>','1335669281130','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;" title="ver <?php echo Project_StaticData::getMarkerContentType($value->type);?>"><?php echo $value->title; ?></a>
			<br/>
			<small>
				<?php echo  stripslashes(sprintf( '%s - %s - %s/%s',$value->address,$value->neighborhood, $value->city, Project_StaticData::getBrasilianStates($value->state))); ?><br/>
				<?php echo date('d/m/Y', strtotime($value->created_at)); ?>
			</small>
		</td>
		<td style="vertical-align: middle;">
			<?php echo stripslashes($value->name); ?>
		</td>
		
		<td class="header" style="vertical-align: middle;">
			<a href="<?php echo $delete_url; ?>" title="Deletar" class="delete"><img style="border:none;" src="<?php echo URL; ?>/backend/design/ico-delete.gif" class="ico" alt="Deletar" /></a>
		</td>
	</tr>
	<?php endforeach; ?>
</tbody>
</table>


<!-- paginação -->
<?php echo $this->paginationControl($this->points ,'Sliding' ,'partials/paginator.phtml', array( 'params' => $this->params)); ?>
<!-- /paginação -->



<?php else: ?>
<p>Nenhum item cadastrado.</p>
<?php endif;?>