<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en" />
	<meta name="robots" content="noindex,nofollow" />
	<link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/reset.css" /> <!-- RESET -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/main.css" /> <!-- MAIN STYLE SHEET -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/2col.css" title="2col" /> <!-- DEFAULT: 2 COLUMNS -->
	<link rel="alternate stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/1col.css" title="1col" /> <!-- ALTERNATE: 1 COLUMN -->
	<!--[if lte IE 6]><link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/main-ie6.css" /><![endif]--> <!-- MSIE6 -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/style.css" /> <!-- GRAPHIC THEME -->
	<link rel="stylesheet" media="screen,projection" type="text/css" href="<?php echo URL; ?>/backend/css/mystyle.css" /> <!-- WRITE YOUR CSS CODE HERE -->
	
	<title>Login</title>
</head>

<body id="login">

<div id="main-02">

	<div id="login-top"></div>

	<div id="login-box">

		<!-- Logo -->
		<p class="nom t-center"><a href="<?php echo URL; ?>" ><img src="<?php echo URL. '/images/logo-nos-midia-v2.png'; ?>" alt="Nós Midia" title="Visit Site" /></a></p>

		<!-- Messages -->
<!--		<p class="msg error">The password you have entered is incorrect. <a href="#">Forgot password?</a></p>-->
		
		

		<?php echo $this->formLoginAdmin; ?><br />

	</div> <!-- /login-box -->

	<div id="login-bottom"></div>

</div> <!-- /main -->

</body>
</html>

